# https://atcoder.jp/ranking 2023-08-19 Japan <=30th
[members.heno]
atcoder = "heno239"
codeforces = "heno239"
x = "heno_code"

[members.hitonanode]
atcoder = "hitonanode"
codeforces = "hitonanode"
x = "rsat__m"

[members.hos]
atcoder = "hos_lyric"
codeforces = "hos.lyric"
x = "hos_lyric"

[members.semiexp]
atcoder = "semiexp"
codeforces = "semiexp"
x = "semiexp"

[members.snuke]
atcoder = "snuke"
codeforces = "snuke"
x = "snuke_"

[members.tatyam]
atcoder = "tatyam"
codeforces = "tatyam"
x = "tatyam_prime"
